LatinStudyTool: Senior-IA-Driver.cpp File Reference
Senior-IA-Driver.cpp File Reference
The driver that creates the UI, starts up the program, and acts as the main loop.
#include "StartUpCommands.h"
#include <windows.h>
Functions
LRESULT CALLBACK WndProc (HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
int WINAPI WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
Variables
std::map< std::string, class LitUnit > IBmap
std::map< std::string, class LitUnit > APmap
const char g_szClassName [] = "myWindowClass"
Detailed Description
The driver that creates the UI, starts up the program, and acts as the main loop.
Definition in file Senior-IA-Driver.cpp.
Function Documentation
WinMain()
int WINAPI WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
Definition at line 30 of file Senior-IA-Driver.cpp.
References APmap, g_szClassName, IBmap, startupLit(), startupStages(), and WndProc().
WndProc()
LRESULT CALLBACK WndProc (HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
Definition at line 14 of file Senior-IA-Driver.cpp.
Referenced by WinMain().
Variable Documentation
APmap
std::map<std::string, class LitUnit> APmap
Definition at line 5 of file Senior-IA-Driver.cpp.
Referenced by startupLit(), and WinMain().
g_szClassName
const char g_szClassName[] = "myWindowClass"
Definition at line 6 of file Senior-IA-Driver.cpp.
Referenced by WinMain().
IBmap
std::map<std::string, class LitUnit> IBmap
Definition at line 4 of file Senior-IA-Driver.cpp.
Referenced by startupLit(), and WinMain().