Latin Study Tool: StartUpCommands.cpp File Reference
StartUpCommands.cpp File Reference
The source code file that contains methods used by the driver during program startup.
#include "StartUpCommands.h"
#include <iostream>
Functions
std::vector< MeaningUnit > readInLines (std::string meter, std::ifstream &litfile, int numUnits)
std::vector< PoeticDevice > readInDevices (std::string title)
void startupLit (std::map< std::string, class LitUnit > &IBmap, std::map< std::string, class LitUnit > &APmap)
The startup method that loads all of the literature data into the program from files.
void startupStages ()
Detailed Description
The source code file that contains methods used by the driver during program startup.
Definition in file StartUpCommands.cpp.
Function Documentation
readInDevices()
std::vector<PoeticDevice> readInDevices (std::string title)
Definition at line 69 of file StartUpCommands.cpp.
Referenced by startupLit().
readInLines()
std::vector<MeaningUnit> readInLines (std::string meter, std::ifstream & litfile, int numUnits)
Definition at line 11 of file StartUpCommands.cpp.
Referenced by startupLit().
startupLit()
void startupLit (std::map< std::string, class LitUnit > & IBmap, std::map< std::string, class LitUnit > & APmap)
The startup method that loads all of the literature data into the program from files.
This method is given two blank maps, one for IB literature and one for AP literature, and then reads in the data from files in the data folder. It starts by opening the LitNames.txt file, which contains the number of IB and AP literatures as well as the name of each literature. For each piece of literature, a LitUnit is constructed by reading in from [title].txt and [title]PD.txt. This LitUnit is then mapped to its title in the correct map.
See also
LitNames.txt
LitUnit
Parameters
IBmap The map that holds all the IB literatures
APmap The map that holds all the AP literatures
Definition at line 106 of file StartUpCommands.cpp.
References APmap, IBmap, readInDevices(), and readInLines().
Referenced by WinMain().
startupStages()
void startupStages ()
Definition at line 169 of file StartUpCommands.cpp.
Referenced by WinMain().