LatinStudyTool: LitUnit Class Reference
LitUnit Class Reference
The object that holds information for a single piece of literature.
#include <LitUnit.h>
Public Member Functions
LitUnit (std::vector< PoeticDevice > d, std::string a, std::string m, Translator t)
std::string intoString ()
Public Attributes
Translator translator = Translator()
std::vector< PoeticDevice > devices = std::vector<PoeticDevice>()
std::string author
std::string meter
Detailed Description
The object that holds information for a single piece of literature.
This class is the highest level class for the literature section of this program. It stores all the information and methods needed to display the literature on the screen: author, meter, the Latin, its English, and poetic devices. There is one LitUnit per literature.
Definition at line 25 of file LitUnit.h.
Constructor & Destructor Documentation
LitUnit()
LitUnit::LitUnit (std::vector< PoeticDevice > d, std::string a, std::string m, Translator t)
The constructor that makes a LitUnit.
This constructor does not do anything other than copy the given objects to the corresponding member objects of the LitUnit.
Parameters
d The vector<PoeticDevices> that is used to create the devices object.
a The string that holds the author.
m The string that holds the meter.
t The Translator for this section.
See also
devices
author
meter
translator
Definition at line 3 of file LitUnit.cpp.
References author, devices, meter, and translator.
Member Function Documentation
intoString()
std::string LitUnit::intoString ()
A method that converts the LitUnit into a string.
The author and meter are saved on the first two lines of the string, then the PoeticDevices are saved to the next lines, then the Translator is saved. The PoeticDevices and Translator are converted to strings by thier own intoString() method.
See also
std::string Translator::intoString()
std::string PoeticDevice::intoString()
Definition at line 12 of file LitUnit.cpp.
References author, devices, Translator::intoString(), meter, and translator.
Member Data Documentation
author
std::string LitUnit::author
A string that holds the author of this literature section.
Definition at line 46 of file LitUnit.h.
Referenced by intoString(), and LitUnit().
devices
std::vector<PoeticDevice> LitUnit::devices = std::vector<PoeticDevice>()
A vector of PoeticDevices to hold the poetic devices of this section.
The devices object holds each poetic device and where it appears in this section. They are stored in order of appearance.
Definition at line 41 of file LitUnit.h.
Referenced by intoString(), and LitUnit().
meter
std::string LitUnit::meter
A string that holds the meter of this literature section.
If the literature is poetry, this string holds what meter the poetry is in. If it is prose, this string holds "prose".
Definition at line 52 of file LitUnit.h.
Referenced by intoString(), and LitUnit().
translator
Translator LitUnit::translator = Translator()
A Translator that stores and tracks the Latin and English of the section.
The translator object stores all of the Latin as well as its translated English. It also tracks at what point in the section the user is reading at, and updates a string to show what the user needs to see.
See also
Translator.h
Translator
Definition at line 34 of file LitUnit.h.
Referenced by intoString(), and LitUnit().
The documentation for this class was generated from the following files:
LitUnit.h
LitUnit.cpp